### ISSUE TITLE
receiving words without confirming my email (can't unsubscribe)

### ISSUE THREAD

**Issue by ivica-k** [em-shea/vocab#14]
Hi Emily,

I was exploring your application code and functionality so I subscribed to a list. I never confirmed my email address and yet I'm receiving daily words.

Also the "Unsubscribe" functionality is not working and is returning a 502, most probably because my user was not found in the DB.

**Comment by ivica-k** [comment]
Just a gentle ping @em-shea , I'm still receiving daily words and I can't unsubscribe.

**Comment by em-shea** [comment]
Thanks for letting me know! I found the problem, '+' characters in email addresses were getting dropped during the unsubscribe API call. I've manually unsubscribed you and am working on the bug fix.

**Comment by ivica-k** [comment]
Thank you.

**Comment by em-shea** [comment]
The latest release fixes this issue - I've added URL encoding so the unsubscribe links from emails will preserve special characters. Thanks!
